[vue] TS fix: use type imports in @collabkit/client
fixes "error TS1444: 'Store' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled."
(preserveValueImports needs to be enabled when using TS with Vue)